apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enterprise-portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "enterprise-portal.name" . }}
    helm.sh/chart: {{ include "enterprise-portal.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "enterprise-portal.name" . }}
    app.kubernetes.io/version: ${project.version}
    app: {{ include "enterprise-portal.fullname" . }}  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "enterprise-portal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}      
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "enterprise-portal.name" . }}
        helm.sh/chart: {{ include "enterprise-portal.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: {{ include "enterprise-portal.name" . }}
        app.kubernetes.io/version: ${project.version}
        app: {{ include "enterprise-portal.fullname" . }}      
    spec:
      imagePullSecrets: 
        - name: {{ .Values.image.imagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: http-ws
              containerPort: 81
              protocol: TCP
          resources:
{{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
